const marioTerms = {
	characters: [
		'Mario',
		'Luigi',
		'Princess Peach',
		'Bowser',
		'Yoshi',
		'Toad',
		'Donkey Kong',
		'Wario',
		'Waluigi',
		'Rosalina',
		'Daisy',
		'Toadette',
		'Birdo',
	],
	enemies: [
		'Goomba',
		'Koopa Troopa',
		'Bob-omb',
		'Bullet Bill',
		'Chain Chomp',
		'Piranha Plant',
		'Boo',
		'Shy Guy',
		'Hammer Bro',
		'Lakitu',
		'Magikoopa',
		'Wiggler',
		'Thwomp',
		'Dry Bones',
		'Buzzy Beetle',
	],
	powerups: [
		'Super Mushroom',
		'Fire Flower',
		'Star Power',
		'1-Up Mushroom',
		'Super Star',
		'Tanooki Suit',
		'Cape Feather',
		'Propeller Mushroom',
		'P-Wing',
		'Hammer Suit',
		'Boomerang Flower',
		'Ice Flower',
		'Mega Mushroom',
		'Gold Flower',
		'Blue Shell',
	],
	games: [
		'Super Mario World',
		'Super Mario Bros.',
		'Super Mario 64',
		'Super Mario Sunshine',
		'Super Mario Galaxy',
		'New Super Mario Bros.',
		'Super Mario 3D Land',
		'New Super Mario Bros. U',
		'Super Mario 3D World',
		'Super Mario Odyssey',
		'Super Mario Maker',
		'Super Mario Run',
		'Mario Kart 8',
		'Mario Party',
		'Mario Tennis',
		'Mario Golf',
	],
	locations: [
		'Mushroom Kingdom',
		"Yoshi's Island",
		'Donut Plains',
		'Delfino Plaza',
		'Comet Observatory',
		"Peach's Castle",
		"Bowser's Castle",
		'Star Road',
		'Toad Town',
		'Bob-omb Battlefield',
		"Whomp's Fortress",
		'Cool, Cool Mountain',
		'Tick Tock Clock',
		'Ricco Harbor',
		'Gusty Garden Galaxy',
		'New Donk City',
		'Hyrule Circuit',
		'Rainbow Road',
	],
};

function getMarioTerm() {
	const termCategories = Object.keys(marioTerms);
	const randomCategory = termCategories[Math.floor(Math.random() * termCategories.length)];
	const terms = marioTerms[randomCategory];
	const randomTerm = terms[Math.floor(Math.random() * terms.length)];
	return randomTerm;
}

module.exports = {
	marioTerms,
	getMarioTerm,
};
